-- Contract for local development; compare with the official AWS schema before deployment.
CREATE TABLE bitacora_logs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 accion VARCHAR(50) NOT NULL,
 fecha_hora TIMESTAMP NOT NULL,
 usuario_responsable VARCHAR(50) NOT NULL,
 entidad VARCHAR(50) NOT NULL,
 entidad_id BIGINT NOT NULL,
 ip_origen VARCHAR(45)
);
CREATE INDEX idx_bitacora_entidad_fecha ON bitacora_logs(entidad, entidad_id, fecha_hora);
INSERT INTO permisos(modulo, pantalla, accion, descripcion)
VALUES ('SEGURIDAD', 'USUARIOS', 'ESCRITURA', 'Administrar cuentas de usuarios')
ON CONFLICT (modulo,pantalla,accion) DO NOTHING;
INSERT INTO roles(nombre, descripcion) VALUES ('ADMIN', 'Administrador del sistema') ON CONFLICT(nombre) DO NOTHING;
INSERT INTO rol_permisos(rol_id, permiso_id)
SELECT r.id,p.id FROM roles r CROSS JOIN permisos p
WHERE upper(r.nombre) IN ('ADMIN','ADMINISTRADOR') AND p.modulo='SEGURIDAD' AND p.pantalla='USUARIOS' AND p.accion='ESCRITURA'
ON CONFLICT DO NOTHING;
